#include "dsk.h"
#include "dsk-tls-private.h"

const DskTlsCipherSuiteCode dsk_tls_cipher_suite_codes[] = {
  DSK_TLS_CIPHER_SUITE_TLS_AES_128_GCM_SHA256,
  DSK_TLS_CIPHER_SUITE_TLS_AES_256_GCM_SHA384,
  DSK_TLS_CIPHER_SUITE_TLS_CHACHA20_POLY1305_SHA256,
  DSK_TLS_CIPHER_SUITE_TLS_AES_128_CCM_SHA256,
  DSK_TLS_CIPHER_SUITE_TLS_AES_128_CCM_8_SHA256,
};
size_t dsk_tls_n_cipher_suite_codes = DSK_N_ELEMENTS (dsk_tls_cipher_suite_codes);
const DskTlsNamedGroup dsk_tls_named_groups[] = {
  DSK_TLS_NAMED_GROUP_X25519,
  DSK_TLS_NAMED_GROUP_X448,
  DSK_TLS_NAMED_GROUP_FFDHE2048,
  DSK_TLS_NAMED_GROUP_FFDHE3072,
  DSK_TLS_NAMED_GROUP_FFDHE4096,
  DSK_TLS_NAMED_GROUP_FFDHE6144,
  DSK_TLS_NAMED_GROUP_FFDHE8192,
  DSK_TLS_NAMED_GROUP_SECP256R1,
  DSK_TLS_NAMED_GROUP_SECP384R1,
  DSK_TLS_NAMED_GROUP_SECP521R1,
};
size_t dsk_tls_n_named_groups = DSK_N_ELEMENTS (dsk_tls_named_groups);
