#! /usr/bin/perl

my $mode = $ARGV[0];
$mode = 'c' unless defined $mode;

my @table = (
  [ "signature_md5_rsa",           "1.2.840.113549.1.1.4"   ],
  [ "signature_sha1_rsa",          "1.2.840.113549.1.1.5"   ],
  [ "signature_sha256_rsa",        "1.2.840.113549.1.1.11"  ],
  [ "signature_sha384_rsa",        "1.2.840.113549.1.1.12"  ],
  [ "signature_sha512_rsa",        "1.2.840.113549.1.1.13"  ],
  [ "signature_rsapss",            "1.2.840.113549.1.1.10"  ],
  [ "signature_dsa_with_sha1",     "1.2.840.10040.4.3"      ],
  [ "signature_dsa_with_sha256",   "2.16.840.1.101.3.4.3.2" ],
  [ "signature_ecdsa_with_sha1",   "1.2.840.10045.4.1"      ],
  [ "signature_ecdsa_with_sha256", "1.2.840.10045.4.3.2"    ],
  [ "signature_ecdsa_with_sha384", "1.2.840.10045.4.3.3"    ],
  [ "signature_ecdsa_with_sha512", "1.2.840.10045.4.3.4"    ],
  [ "signature_ed25519",           "1.3.101.112"            ],
);

if ($mode eq 'c') {
  print "/*\n";
  print " * Generated by $0\n";
  print " */\n\n";
  print "#include \"../dsk.h\"\n";
}

my @offsets = ();
print "const uint32_t dsk_oid_heap[] = {\n" if ($mode eq 'c');
my $offset = 0;
for (@table) {
  my $e = $_;
  my $dotted = $e->[1];
  my $name = $e->[0];
  my $pieces = $dotted =~ tr/././ + 1;
  my $copy = $dotted;
  $copy =~ s/\./,/g;
  print "  $pieces, $copy,    /* $name */\n" if ($mode eq 'c');
  push @$e, $offset;
  $offset += 1 + $pieces;
}
print "};\n\n" if ($mode eq 'c');

for (@table) {
  my $e = $_;
  my $name = $e->[0];
  my $offset = $e->[2];
  #print "DskOID *dsk_tls_oid__$name = (DskOID *) (dsk_tls_oid_heap + $offset);\n" if ($mode eq 'c')
  #print "extern DskOID *dsk_tls_oid__$name;\n",
  print "#define dsk_oid__$name   \\\n                             ((DskOID*)(dsk_tls_oid_heap + $offset))\n" if ($mode eq 'h')
}
